app = "api-introspection-worker"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile.worker"

[env]
  PYTHONUNBUFFERED = "1"

# Use shared CPU
[vm]
  cpu_kind = "shared"
  cpu_shares = 1
  memory_mb = 256

[processes]
  worker = "poetry run celery -A src.tasks.celery_worker worker --loglevel=info --concurrency=2"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["worker"]
  min_machines_running = 1

  [services.concurrency]
    type = "connections"
    hard_limit = 5
    soft_limit = 3

  [[services.tcp_checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    restart_limit = 0
