app = "api-introspection-worker"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile.worker"

[env]
  PYTHONUNBUFFERED = "1"
  ENV = "production"
  LOG_LEVEL = "INFO"
  # REDIS_URL will be automatically set when you attach Redis

# Use shared CPU
[vm]
  cpu_kind = "shared"
  cpu_shares = 1
  memory_mb = 256

[processes]
  app = "poetry run celery -A src.tasks.celery_worker worker --loglevel=info --concurrency=2"

# Simple process-based deployment
[deploy]
  strategy = "immediate"
