openapi: 3.0.3
info:
  title: LLM API Inspector
  version: 0.1.0
  description: |
    Upload OpenAPI specs and query them using natural language.
    This API parses OpenAPI files and lets you explore or summarize endpoints via LLM.

paths:
  /spec/upload:
    post:
      summary: Upload an OpenAPI spec (YAML or JSON)
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "200":
          description: Spec uploaded and parsed
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The unique identifier for the uploaded spec

  /spec/{id}/summary:
    get:
      summary: Retrieve a JSON summary of the spec
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Summary returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  summary:
                    type: string

  /spec/{id}/export:
    get:
      summary: Download the summary in various formats
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
        - in: query
          name: format
          required: true
          schema:
            type: string
            enum: [html, markdown, docx]
            default: markdown
      responses:
        "200":
          description: Summary exported in requested format
          content:
            text/html:
              schema:
                type: string
            text/markdown:
              schema:
                type: string
            application/vnd.openxmlformats-officedocument.wordprocessingml.document:
              schema:
                type: string
                format: binary
