name: Fly Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggers

jobs:
  deploy-api:
    name: Deploy API
    runs-on: ubuntu-latest
    concurrency: deploy-api
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@v1
      - name: Deploy API
        run: flyctl deploy --config fly.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-worker:
    name: Deploy Worker
    runs-on: ubuntu-latest
    concurrency: deploy-worker
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@v1
      - name: Deploy Worker
        run: flyctl deploy --config fly.worker.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
